### ISSUE TITLE
Isn't this just `loadstring`-ing the byte code

### ISSUE THREAD

**Issue by AsynchronousAI** [hugomg/lua-aot-5.4#10]
```c
int LUAOT_LUAOPEN_NAME(lua_State *L) {
    int ok = luaL_loadstring(L, LUAOT_MODULE_SOURCE_CODE);
    switch (ok) {
      case LUA_OK:
        /* No errors */
        break;
      case LUA_ERRSYNTAX:
        fprintf(stderr, "syntax error in bundled source code.\n");
        exit(1);
        break;
      case LUA_ERRMEM:
        fprintf(stderr, "memory allocation (out-of-memory) error in bundled source code.\n");
        exit(1);
        break;
      default:
        fprintf(stderr, "unknown error. This should never happen\n");
        exit(1);
    }

    LClosure *cl = (void *) lua_topointer(L, -1);
    bind_magic(cl->p);

    lua_call(L, 0, 1);
    return 1;
}
```

**Comment by hugomg** [comment]
There's more to it...

Our compiler is based on partial evaluation, so it still needs to create a Lua Closure object for the function. That's the `LClosure *cl` object. Loadstring is the easiest way to create this closure.

However, we do not use the bytecode when we run the function. If the function's `aot_implementation` is set, it will evaluate the function using that, instead of the regular Lua interpreter. The `bind_magic` function initializes these fields.

IIRC, the only time the bytecode will be used is if someone needs to generate a stack trace.
